import { Element } from '@/types'

export const ELEMENTS: Element[] = [
  // Period 1
  { symbol: 'H',  name: '수소',     number: 1,   group: 1,  period: 1, category: 'nonmetal',        color: '#FF6B6B' },
  { symbol: 'He', name: '헬륨',     number: 2,   group: 18, period: 1, category: 'noble-gas',        color: '#A8E6CF' },
  // Period 2
  { symbol: 'Li', name: '리튬',     number: 3,   group: 1,  period: 2, category: 'alkali-metal',     color: '#FFB347' },
  { symbol: 'Be', name: '베릴륨',   number: 4,   group: 2,  period: 2, category: 'alkaline-earth',   color: '#87CEEB' },
  { symbol: 'B',  name: '붕소',     number: 5,   group: 13, period: 2, category: 'metalloid',        color: '#DDA0DD' },
  { symbol: 'C',  name: '탄소',     number: 6,   group: 14, period: 2, category: 'nonmetal',         color: '#FF6B6B' },
  { symbol: 'N',  name: '질소',     number: 7,   group: 15, period: 2, category: 'nonmetal',         color: '#FF6B6B' },
  { symbol: 'O',  name: '산소',     number: 8,   group: 16, period: 2, category: 'nonmetal',         color: '#FF6B6B' },
  { symbol: 'F',  name: '플루오린', number: 9,   group: 17, period: 2, category: 'halogen',          color: '#98FB98' },
  { symbol: 'Ne', name: '네온',     number: 10,  group: 18, period: 2, category: 'noble-gas',        color: '#A8E6CF' },
  // Period 3
  { symbol: 'Na', name: '나트륨',   number: 11,  group: 1,  period: 3, category: 'alkali-metal',     color: '#FFB347' },
  { symbol: 'Mg', name: '마그네슘', number: 12,  group: 2,  period: 3, category: 'alkaline-earth',   color: '#87CEEB' },
  { symbol: 'Al', name: '알루미늄', number: 13,  group: 13, period: 3, category: 'post-transition',  color: '#B0C4DE' },
  { symbol: 'Si', name: '규소',     number: 14,  group: 14, period: 3, category: 'metalloid',        color: '#DDA0DD' },
  { symbol: 'P',  name: '인',       number: 15,  group: 15, period: 3, category: 'nonmetal',         color: '#FF6B6B' },
  { symbol: 'S',  name: '황',       number: 16,  group: 16, period: 3, category: 'nonmetal',         color: '#FF6B6B' },
  { symbol: 'Cl', name: '염소',     number: 17,  group: 17, period: 3, category: 'halogen',          color: '#98FB98' },
  { symbol: 'Ar', name: '아르곤',   number: 18,  group: 18, period: 3, category: 'noble-gas',        color: '#A8E6CF' },
  // Period 4
  { symbol: 'K',  name: '칼륨',     number: 19,  group: 1,  period: 4, category: 'alkali-metal',     color: '#FFB347' },
  { symbol: 'Ca', name: '칼슘',     number: 20,  group: 2,  period: 4, category: 'alkaline-earth',   color: '#87CEEB' },
  { symbol: 'Sc', name: '스칸듐',   number: 21,  group: 3,  period: 4, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Ti', name: '타이타늄', number: 22,  group: 4,  period: 4, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'V',  name: '바나듐',   number: 23,  group: 5,  period: 4, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Cr', name: '크롬',     number: 24,  group: 6,  period: 4, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Mn', name: '망간',     number: 25,  group: 7,  period: 4, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Fe', name: '철',       number: 26,  group: 8,  period: 4, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Co', name: '코발트',   number: 27,  group: 9,  period: 4, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Ni', name: '니켈',     number: 28,  group: 10, period: 4, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Cu', name: '구리',     number: 29,  group: 11, period: 4, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Zn', name: '아연',     number: 30,  group: 12, period: 4, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Ga', name: '갈륨',     number: 31,  group: 13, period: 4, category: 'post-transition',  color: '#B0C4DE' },
  { symbol: 'Ge', name: '저마늄',   number: 32,  group: 14, period: 4, category: 'metalloid',        color: '#DDA0DD' },
  { symbol: 'As', name: '비소',     number: 33,  group: 15, period: 4, category: 'metalloid',        color: '#DDA0DD' },
  { symbol: 'Se', name: '셀레늄',   number: 34,  group: 16, period: 4, category: 'nonmetal',         color: '#FF6B6B' },
  { symbol: 'Br', name: '브로민',   number: 35,  group: 17, period: 4, category: 'halogen',          color: '#98FB98' },
  { symbol: 'Kr', name: '크립톤',   number: 36,  group: 18, period: 4, category: 'noble-gas',        color: '#A8E6CF' },
  // Period 5
  { symbol: 'Rb', name: '루비듐',   number: 37,  group: 1,  period: 5, category: 'alkali-metal',     color: '#FFB347' },
  { symbol: 'Sr', name: '스트론튬', number: 38,  group: 2,  period: 5, category: 'alkaline-earth',   color: '#87CEEB' },
  { symbol: 'Y',  name: '이트륨',   number: 39,  group: 3,  period: 5, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Zr', name: '지르코늄', number: 40,  group: 4,  period: 5, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Nb', name: '나이오븀', number: 41,  group: 5,  period: 5, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Mo', name: '몰리브덴', number: 42,  group: 6,  period: 5, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Tc', name: '테크네튬', number: 43,  group: 7,  period: 5, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Ru', name: '루테늄',   number: 44,  group: 8,  period: 5, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Rh', name: '로듐',     number: 45,  group: 9,  period: 5, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Pd', name: '팔라듐',   number: 46,  group: 10, period: 5, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Ag', name: '은',       number: 47,  group: 11, period: 5, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Cd', name: '카드뮴',   number: 48,  group: 12, period: 5, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'In', name: '인듐',     number: 49,  group: 13, period: 5, category: 'post-transition',  color: '#B0C4DE' },
  { symbol: 'Sn', name: '주석',     number: 50,  group: 14, period: 5, category: 'post-transition',  color: '#B0C4DE' },
  { symbol: 'Sb', name: '안티모니', number: 51,  group: 15, period: 5, category: 'metalloid',        color: '#DDA0DD' },
  { symbol: 'Te', name: '텔루륨',   number: 52,  group: 16, period: 5, category: 'metalloid',        color: '#DDA0DD' },
  { symbol: 'I',  name: '아이오딘', number: 53,  group: 17, period: 5, category: 'halogen',          color: '#98FB98' },
  { symbol: 'Xe', name: '제논',     number: 54,  group: 18, period: 5, category: 'noble-gas',        color: '#A8E6CF' },
  // Period 6
  { symbol: 'Cs', name: '세슘',     number: 55,  group: 1,  period: 6, category: 'alkali-metal',     color: '#FFB347' },
  { symbol: 'Ba', name: '바륨',     number: 56,  group: 2,  period: 6, category: 'alkaline-earth',   color: '#87CEEB' },
  { symbol: 'La', name: '란타넘',   number: 57,  group: 3,  period: 6, category: 'lanthanide',       color: '#FFD700' },
  { symbol: 'Hf', name: '하프늄',   number: 72,  group: 4,  period: 6, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Ta', name: '탄탈럼',   number: 73,  group: 5,  period: 6, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'W',  name: '텅스텐',   number: 74,  group: 6,  period: 6, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Re', name: '레늄',     number: 75,  group: 7,  period: 6, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Os', name: '오스뮴',   number: 76,  group: 8,  period: 6, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Ir', name: '이리듐',   number: 77,  group: 9,  period: 6, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Pt', name: '백금',     number: 78,  group: 10, period: 6, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Au', name: '금',       number: 79,  group: 11, period: 6, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Hg', name: '수은',     number: 80,  group: 12, period: 6, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Tl', name: '탈륨',     number: 81,  group: 13, period: 6, category: 'post-transition',  color: '#B0C4DE' },
  { symbol: 'Pb', name: '납',       number: 82,  group: 14, period: 6, category: 'post-transition',  color: '#B0C4DE' },
  { symbol: 'Bi', name: '비스무트', number: 83,  group: 15, period: 6, category: 'post-transition',  color: '#B0C4DE' },
  { symbol: 'Po', name: '폴로늄',   number: 84,  group: 16, period: 6, category: 'metalloid',        color: '#DDA0DD' },
  { symbol: 'At', name: '아스타틴', number: 85,  group: 17, period: 6, category: 'halogen',          color: '#98FB98' },
  { symbol: 'Rn', name: '라돈',     number: 86,  group: 18, period: 6, category: 'noble-gas',        color: '#A8E6CF' },
  // Period 7
  { symbol: 'Fr', name: '프랑슘',   number: 87,  group: 1,  period: 7, category: 'alkali-metal',     color: '#FFB347' },
  { symbol: 'Ra', name: '라듐',     number: 88,  group: 2,  period: 7, category: 'alkaline-earth',   color: '#87CEEB' },
  { symbol: 'Ac', name: '악티늄',   number: 89,  group: 3,  period: 7, category: 'actinide',         color: '#E9967A' },
  { symbol: 'Rf', name: '러더포듐', number: 104, group: 4,  period: 7, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Db', name: '더브늄',   number: 105, group: 5,  period: 7, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Sg', name: '시보귬',   number: 106, group: 6,  period: 7, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Bh', name: '보륨',     number: 107, group: 7,  period: 7, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Hs', name: '하슘',     number: 108, group: 8,  period: 7, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Mt', name: '마이트너륨',number: 109, group: 9, period: 7, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Ds', name: '다름슈타튬',number: 110, group: 10,period: 7, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Rg', name: '뢴트게늄', number: 111, group: 11, period: 7, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Cn', name: '코페르니슘',number: 112, group: 12,period: 7, category: 'transition',       color: '#FFC0CB' },
  { symbol: 'Nh', name: '니호늄',   number: 113, group: 13, period: 7, category: 'post-transition',  color: '#B0C4DE' },
  { symbol: 'Fl', name: '플레로븀', number: 114, group: 14, period: 7, category: 'post-transition',  color: '#B0C4DE' },
  { symbol: 'Mc', name: '모스코븀', number: 115, group: 15, period: 7, category: 'post-transition',  color: '#B0C4DE' },
  { symbol: 'Lv', name: '리버모륨', number: 116, group: 16, period: 7, category: 'post-transition',  color: '#B0C4DE' },
  { symbol: 'Ts', name: '테네신',   number: 117, group: 17, period: 7, category: 'halogen',          color: '#98FB98' },
  { symbol: 'Og', name: '오가네손', number: 118, group: 18, period: 7, category: 'noble-gas',        color: '#A8E6CF' },
  // Lanthanides
  { symbol: 'Ce', name: '세륨',     number: 58,  group: 0,  period: 6, category: 'lanthanide',       color: '#FFD700' },
  { symbol: 'Pr', name: '프라세오디뮴',number: 59,group: 0, period: 6, category: 'lanthanide',       color: '#FFD700' },
  { symbol: 'Nd', name: '네오디뮴', number: 60,  group: 0,  period: 6, category: 'lanthanide',       color: '#FFD700' },
  { symbol: 'Pm', name: '프로메튬', number: 61,  group: 0,  period: 6, category: 'lanthanide',       color: '#FFD700' },
  { symbol: 'Sm', name: '사마륨',   number: 62,  group: 0,  period: 6, category: 'lanthanide',       color: '#FFD700' },
  { symbol: 'Eu', name: '유로퓸',   number: 63,  group: 0,  period: 6, category: 'lanthanide',       color: '#FFD700' },
  { symbol: 'Gd', name: '가돌리늄', number: 64,  group: 0,  period: 6, category: 'lanthanide',       color: '#FFD700' },
  { symbol: 'Tb', name: '터븀',     number: 65,  group: 0,  period: 6, category: 'lanthanide',       color: '#FFD700' },
  { symbol: 'Dy', name: '디스프로슘',number: 66, group: 0,  period: 6, category: 'lanthanide',       color: '#FFD700' },
  { symbol: 'Ho', name: '홀뮴',     number: 67,  group: 0,  period: 6, category: 'lanthanide',       color: '#FFD700' },
  { symbol: 'Er', name: '어븀',     number: 68,  group: 0,  period: 6, category: 'lanthanide',       color: '#FFD700' },
  { symbol: 'Tm', name: '툴륨',     number: 69,  group: 0,  period: 6, category: 'lanthanide',       color: '#FFD700' },
  { symbol: 'Yb', name: '이터븀',   number: 70,  group: 0,  period: 6, category: 'lanthanide',       color: '#FFD700' },
  { symbol: 'Lu', name: '루테튬',   number: 71,  group: 0,  period: 6, category: 'lanthanide',       color: '#FFD700' },
  // Actinides
  { symbol: 'Th', name: '토륨',     number: 90,  group: 0,  period: 7, category: 'actinide',         color: '#E9967A' },
  { symbol: 'Pa', name: '프로탁티늄',number: 91, group: 0,  period: 7, category: 'actinide',         color: '#E9967A' },
  { symbol: 'U',  name: '우라늄',   number: 92,  group: 0,  period: 7, category: 'actinide',         color: '#E9967A' },
  { symbol: 'Np', name: '넵투늄',   number: 93,  group: 0,  period: 7, category: 'actinide',         color: '#E9967A' },
  { symbol: 'Pu', name: '플루토늄', number: 94,  group: 0,  period: 7, category: 'actinide',         color: '#E9967A' },
  { symbol: 'Am', name: '아메리슘', number: 95,  group: 0,  period: 7, category: 'actinide',         color: '#E9967A' },
  { symbol: 'Cm', name: '퀴륨',     number: 96,  group: 0,  period: 7, category: 'actinide',         color: '#E9967A' },
  { symbol: 'Bk', name: '버클륨',   number: 97,  group: 0,  period: 7, category: 'actinide',         color: '#E9967A' },
  { symbol: 'Cf', name: '캘리포늄', number: 98,  group: 0,  period: 7, category: 'actinide',         color: '#E9967A' },
  { symbol: 'Es', name: '아인슈타이늄',number:99, group: 0, period: 7, category: 'actinide',         color: '#E9967A' },
  { symbol: 'Fm', name: '페르뮴',   number: 100, group: 0,  period: 7, category: 'actinide',         color: '#E9967A' },
  { symbol: 'Md', name: '멘델레븀', number: 101, group: 0,  period: 7, category: 'actinide',         color: '#E9967A' },
  { symbol: 'No', name: '노벨륨',   number: 102, group: 0,  period: 7, category: 'actinide',         color: '#E9967A' },
  { symbol: 'Lr', name: '로렌슘',   number: 103, group: 0,  period: 7, category: 'actinide',         color: '#E9967A' },
]

export const getElementBySymbol = (symbol: string) =>
  ELEMENTS.find(e => e.symbol === symbol)

export const CATEGORY_COLORS: Record<string, string> = {
  'alkali-metal':    '#FFB34733',
  'alkaline-earth':  '#87CEEB33',
  'transition':      '#FFC0CB33',
  'post-transition': '#B0C4DE33',
  'metalloid':       '#DDA0DD33',
  'nonmetal':        '#FF6B6B33',
  'halogen':         '#98FB9833',
  'noble-gas':       '#A8E6CF33',
  'lanthanide':      '#FFD70033',
  'actinide':        '#E9967A33',
}
