import { Reaction } from '@/types'

export const REACTIONS: Omit<Reaction, 'id' | 'secondary_color' | 'is_pubchem'>[] = [
  { elements: ["Na", "N"], ratios: [1, 3], product_formula: 'NaN₃', product_name: '아지드화나트륨(에어백)', reaction_type: 'explosion', animation: 'explode', color: '#FF4500' },
  { elements: ["Si", "N"], ratios: [3, 4], product_formula: 'Si₃N₄', product_name: '질화규소', reaction_type: 'combustion', animation: 'burn', color: '#E8E8E8' },
  { elements: ["C", "H", "O"], ratios: [3, 8, 3], product_formula: 'C₃H₈O₃', product_name: '글리세롤', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["C", "H", "O"], ratios: [6, 5, 1], product_formula: 'C₆H₅CHO', product_name: '벤즈알데히드', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5DEB3' },
  { elements: ["Ba", "S", "O"], ratios: [1, 1, 4], product_formula: 'BaSO₄', product_name: '중정석(barite)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Fe", "O"], ratios: [3, 4], product_formula: 'Fe₃O₄', product_name: '사산화삼철', reaction_type: 'precipitation', animation: 'sink', color: '#2C1A0A' },
  { elements: ["Ni", "O"], ratios: [1, 1], product_formula: 'NiO', product_name: '산화니켈(II)', reaction_type: 'precipitation', animation: 'sink', color: '#1A3D1A' },
  { elements: ["K", "C", "N"], ratios: [1, 1, 1], product_formula: 'KCN', product_name: '사이안화칼륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["H", "Br", "O"], ratios: [1, 1, 3], product_formula: 'HBrO₃', product_name: '브롬산', reaction_type: 'dissolution', animation: 'dissolve', color: '#E0E8FF' },
  { elements: ["Au", "Cu"], ratios: [3, 1], product_formula: 'Au₃Cu', product_name: '금구리합금', reaction_type: 'combustion', animation: 'burn', color: '#FFD700' },
  { elements: ["Na", "C", "O"], ratios: [2, 1, 3], product_formula: 'Na₂CO₃', product_name: '탄산나트륨(소다)', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["C", "H"], ratios: [7, 16], product_formula: 'C₇H₁₆', product_name: '헵테인', reaction_type: 'combustion', animation: 'burn', color: '#E0E0E0' },
  { elements: ["Ni", "S", "O"], ratios: [1, 1, 4], product_formula: 'NiSO₄', product_name: '황산니켈(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#90EE90' },
  { elements: ["Hg", "Cl"], ratios: [1, 2], product_formula: 'HgCl₂', product_name: '염화수은(II)', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Pb", "O"], ratios: [1, 2], product_formula: 'PbO₂', product_name: '이산화납', reaction_type: 'precipitation', animation: 'sink', color: '#3D2B00' },
  { elements: ["In", "N"], ratios: [1, 1], product_formula: 'InN', product_name: '질화인듐', reaction_type: 'combustion', animation: 'burn', color: '#808080' },
  { elements: ["Pb", "Cl"], ratios: [1, 2], product_formula: 'PbCl₂', product_name: '염화납', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Cu", "Cl"], ratios: [1, 2], product_formula: 'CuCl₂', product_name: '염화구리(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#008B8B' },
  { elements: ["Hg", "C", "N"], ratios: [1, 2, 2], product_formula: 'Hg(CN)₂', product_name: '사이안화수은', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Cl", "O"], ratios: [2, 7], product_formula: 'Cl₂O₇', product_name: '칠산화이염소', reaction_type: 'gas', animation: 'bubble', color: '#F0F0C0' },
  { elements: ["N", "H", "Cl"], ratios: [1, 4, 1], product_formula: 'NH₄Cl', product_name: '염화암모늄', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Ag", "Br"], ratios: [1, 1], product_formula: 'AgBr', product_name: '브롬화은', reaction_type: 'precipitation', animation: 'sink', color: '#FFFACD' },
  { elements: ["Pb", "S", "O"], ratios: [1, 1, 4], product_formula: 'PbSO₄', product_name: '황산납(납축전지)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Zn", "C", "O"], ratios: [1, 1, 3], product_formula: 'ZnCO₃', product_name: '탄산아연', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Cu", "Fe", "S"], ratios: [1, 1, 2], product_formula: 'CuFeS₂', product_name: '황동광(chalcopyrite)', reaction_type: 'precipitation', animation: 'sink', color: '#DAA520' },
  { elements: ["Ra", "O"], ratios: [1, 1], product_formula: 'RaO', product_name: '산화라듐', reaction_type: 'combustion', animation: 'burn', color: '#F0F0F0' },
  { elements: ["Mn", "C", "O"], ratios: [1, 1, 3], product_formula: 'MnCO₃', product_name: '탄산망간(II)', reaction_type: 'precipitation', animation: 'sink', color: '#F5E0D0' },
  { elements: ["C", "H", "N"], ratios: [2, 7, 1], product_formula: 'C₂H₇N', product_name: '에틸아민', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["C", "H", "O"], ratios: [4, 10, 1], product_formula: 'C₄H₉OH', product_name: '뷰탄올', reaction_type: 'combustion', animation: 'burn', color: '#ADD8E6' },
  { elements: ["Na", "S", "O"], ratios: [2, 2, 3], product_formula: 'Na₂S₂O₃', product_name: '티오황산나트륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Na", "Al", "Si", "O"], ratios: [1, 1, 3, 8], product_formula: 'NaAlSi₃O₈', product_name: '조장석', reaction_type: 'precipitation', animation: 'sink', color: '#F5F0E8' },
  { elements: ["Na", "O"], ratios: [2, 1], product_formula: 'Na₂O', product_name: '산화나트륨', reaction_type: 'combustion', animation: 'burn', color: '#F5F5F5' },
  { elements: ["K", "Cl", "O"], ratios: [1, 1, 4], product_formula: 'KClO₄', product_name: '과염소산칼륨', reaction_type: 'explosion', animation: 'explode', color: '#FF6600' },
  { elements: ["Fe", "O", "H"], ratios: [1, 2, 2], product_formula: 'Fe(OH)₂', product_name: '수산화철(II)', reaction_type: 'precipitation', animation: 'sink', color: '#3E7A3E' },
  { elements: ["Sn", "S"], ratios: [1, 2], product_formula: 'SnS₂', product_name: '황화주석(IV)', reaction_type: 'precipitation', animation: 'sink', color: '#FFD700' },
  { elements: ["C", "H", "Cl"], ratios: [1, 3, 1], product_formula: 'CH₃Cl', product_name: '클로로메테인', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["C", "H", "O"], ratios: [2, 4, 2], product_formula: 'CH₃COOH', product_name: '아세트산(식초)', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["C", "H"], ratios: [4, 10], product_formula: 'C₄H₁₀', product_name: '뷰테인', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["Ca", "C", "H", "O"], ratios: [1, 4, 6, 4], product_formula: '(CH₃COO)₂Ca', product_name: '아세트산칼슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["H", "O"], ratios: [2, 2], product_formula: 'H₂O₂', product_name: '과산화수소', reaction_type: 'dissolution', animation: 'colorchange', color: '#ADD8E6' },
  { elements: ["Na", "Cr", "O"], ratios: [2, 2, 7], product_formula: 'Na₂Cr₂O₇', product_name: '중크롬산나트륨', reaction_type: 'color_change', animation: 'colorchange', color: '#FF4500' },
  { elements: ["Li", "S", "O"], ratios: [2, 1, 4], product_formula: 'Li₂SO₄', product_name: '황산리튬', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Al", "Cl"], ratios: [1, 3], product_formula: 'AlCl₃', product_name: '염화알루미늄', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["C", "H", "O"], ratios: [4, 8, 2], product_formula: 'C₃H₇COOH', product_name: '뷰티르산', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["Cu", "I"], ratios: [1, 1], product_formula: 'CuI', product_name: '아이오딘화구리(I)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["C", "H", "N", "O"], ratios: [5, 9, 1, 4], product_formula: 'C₅H₉NO₄', product_name: '글루탐산', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["K", "O"], ratios: [4, 1], product_formula: 'K₄O', product_name: '산화칼륨(반응)', reaction_type: 'explosion', animation: 'explode', color: '#FF4500' },
  { elements: ["Zn", "N", "O"], ratios: [1, 2, 6], product_formula: 'Zn(NO₃)₂', product_name: '질산아연', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Fe", "O"], ratios: [1, 1], product_formula: 'FeO', product_name: '산화철(II)', reaction_type: 'precipitation', animation: 'sink', color: '#1A0A00' },
  { elements: ["Li", "N", "O"], ratios: [1, 1, 3], product_formula: 'LiNO₃', product_name: '질산리튬', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Na", "Cl"], ratios: [1, 1], product_formula: 'NaCl', product_name: '염화나트륨', reaction_type: 'combustion', animation: 'explode', color: '#FF6600' },
  { elements: ["C", "H", "O"], ratios: [7, 6, 3], product_formula: 'C₇H₆O₃', product_name: '살리실산', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["N", "C", "H", "O"], ratios: [3, 1, 5, 6], product_formula: 'C(NO₂)₃H₅', product_name: '니트로글리세린', reaction_type: 'explosion', animation: 'explode', color: '#FF0000' },
  { elements: ["H", "N", "O"], ratios: [3, 1, 3], product_formula: 'HNO₃', product_name: '질산', reaction_type: 'explosion', animation: 'explode', color: '#FF4444' },
  { elements: ["Li", "N"], ratios: [3, 1], product_formula: 'Li₃N', product_name: '질화리튬', reaction_type: 'combustion', animation: 'burn', color: '#FF4500' },
  { elements: ["K", "Cl", "O"], ratios: [2, 2, 3], product_formula: 'KClO₃', product_name: '염소산칼륨', reaction_type: 'explosion', animation: 'explode', color: '#FF0000' },
  { elements: ["Zn", "Mn", "O"], ratios: [1, 1, 2], product_formula: 'ZnMnO₂', product_name: '망간건전지', reaction_type: 'dissolution', animation: 'colorchange', color: '#2F2F2F' },
  { elements: ["C", "H"], ratios: [6, 6], product_formula: 'C₆H₆', product_name: '벤젠', reaction_type: 'combustion', animation: 'burn', color: '#E0E0E0' },
  { elements: ["C", "H", "O"], ratios: [3, 6, 2], product_formula: 'C₂H₅COOH', product_name: '프로피온산', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["P", "O"], ratios: [4, 10], product_formula: 'P₄O₁₀', product_name: '오산화이인', reaction_type: 'gas', animation: 'bubble', color: '#F5F5F5' },
  { elements: ["Zn", "Cl"], ratios: [1, 2], product_formula: 'ZnCl₂', product_name: '염화아연', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["K", "Cl", "O"], ratios: [2, 2, 3], product_formula: 'KClO₃', product_name: '염소산칼륨(불꽃)', reaction_type: 'explosion', animation: 'explode', color: '#FF4444' },
  { elements: ["C", "Cl", "F"], ratios: [1, 2, 2], product_formula: 'CCl₂F₂', product_name: '프레온-12(CFC)', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["C", "H", "Cl"], ratios: [1, 1, 3], product_formula: 'CHCl₃', product_name: '클로로폼', reaction_type: 'dissolution', animation: 'dissolve', color: '#E0E0E0' },
  { elements: ["H", "Cl", "O"], ratios: [1, 1, 4], product_formula: 'HClO₄', product_name: '과염소산', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0FFD0' },
  { elements: ["Co", "O", "H"], ratios: [1, 2, 2], product_formula: 'Co(OH)₂', product_name: '수산화코발트(II)', reaction_type: 'precipitation', animation: 'sink', color: '#FF69B4' },
  { elements: ["Ca", "Br"], ratios: [1, 2], product_formula: 'CaBr₂', product_name: '브롬화칼슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["C", "H"], ratios: [2, 2], product_formula: 'C₂H₂', product_name: '아세틸렌(에타인)', reaction_type: 'combustion', animation: 'burn', color: '#E0E0E0' },
  { elements: ["C", "H", "O"], ratios: [12, 22, 11], product_formula: 'C₁₂H₂₂O₁₁', product_name: '말토스', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5DC' },
  { elements: ["Mn", "S"], ratios: [1, 1], product_formula: 'MnS', product_name: '황화망간', reaction_type: 'precipitation', animation: 'sink', color: '#FFB6C1' },
  { elements: ["Na", "O"], ratios: [4, 1], product_formula: 'Na₄O', product_name: '산화나트륨(반응)', reaction_type: 'explosion', animation: 'explode', color: '#FF6600' },
  { elements: ["Na", "H", "P", "O"], ratios: [2, 1, 1, 4], product_formula: 'Na₂HPO₄', product_name: '인산수소이나트륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Mg", "C", "O"], ratios: [1, 1, 3], product_formula: 'MgCO₃', product_name: '탄산마그네슘', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Ag", "Cl"], ratios: [1, 1], product_formula: 'AgCl', product_name: '염화은', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["K", "Cr", "O"], ratios: [2, 1, 4], product_formula: 'K₂CrO₄', product_name: '크롬산칼륨', reaction_type: 'color_change', animation: 'colorchange', color: '#FFD700' },
  { elements: ["C", "H", "O"], ratios: [6, 14, 6], product_formula: 'C₆H₁₄O₆', product_name: '만니톨', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["Pb", "O"], ratios: [3, 4], product_formula: 'Pb₃O₄', product_name: '사산화삼납', reaction_type: 'precipitation', animation: 'sink', color: '#FF4500' },
  { elements: ["C", "H", "O"], ratios: [6, 6, 6], product_formula: 'C₆H₆O₆', product_name: '아스코르브산(비타민C)', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5DC' },
  { elements: ["C", "H"], ratios: [3, 8], product_formula: 'C₃H₈', product_name: '프로페인', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["Fe", "P", "O"], ratios: [1, 1, 4], product_formula: 'FePO₄', product_name: '인산철(III)', reaction_type: 'precipitation', animation: 'sink', color: '#F5DC90' },
  { elements: ["Zn", "O", "H"], ratios: [1, 2, 2], product_formula: 'Zn(OH)₂', product_name: '수산화아연', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["K", "S", "O"], ratios: [2, 1, 4], product_formula: 'K₂SO₄', product_name: '황산칼륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Sr", "N", "O"], ratios: [1, 2, 6], product_formula: 'Sr(NO₃)₂', product_name: '질산스트론튬', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Na", "O"], ratios: [2, 2], product_formula: 'Na₂O₂', product_name: '과산화나트륨', reaction_type: 'explosion', animation: 'explode', color: '#F5F5DC' },
  { elements: ["Zn", "Se"], ratios: [1, 1], product_formula: 'ZnSe', product_name: '셀렌화아연', reaction_type: 'combustion', animation: 'burn', color: '#FFD700' },
  { elements: ["N", "H"], ratios: [2, 4], product_formula: 'N₂H₄', product_name: '하이드라진', reaction_type: 'explosion', animation: 'explode', color: '#D0E8FF' },
  { elements: ["Ca", "C", "O"], ratios: [1, 1, 3], product_formula: 'CaCO₃', product_name: '방해석(calcite)', reaction_type: 'gas', animation: 'bubble', color: '#F5F5F5' },
  { elements: ["C", "H", "N", "O"], ratios: [1, 4, 2, 1], product_formula: 'CH₄N₂O', product_name: '요소(유레아)', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["Na", "S"], ratios: [2, 1], product_formula: 'Na₂S', product_name: '황화나트륨', reaction_type: 'dissolution', animation: 'colorchange', color: '#F5F5DC' },
  { elements: ["Fe", "S"], ratios: [2, 3], product_formula: 'Fe₂S₃', product_name: '황화철(III)', reaction_type: 'precipitation', animation: 'sink', color: '#1A1A1A' },
  { elements: ["Co", "N", "O"], ratios: [1, 2, 6], product_formula: 'Co(NO₃)₂', product_name: '질산코발트(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#FF69B4' },
  { elements: ["N", "H", "P", "O"], ratios: [3, 12, 1, 4], product_formula: '(NH₄)₃PO₄', product_name: '인산암모늄', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["C", "H", "Cl"], ratios: [2, 3, 3], product_formula: 'C₂H₃Cl₃', product_name: '트라이클로로에테인', reaction_type: 'dissolution', animation: 'dissolve', color: '#E0E0E0' },
  { elements: ["V", "Cl"], ratios: [1, 3], product_formula: 'VCl₃', product_name: '염화바나듐(III)', reaction_type: 'dissolution', animation: 'colorchange', color: '#8B0000' },
  { elements: ["N", "H"], ratios: [1, 3], product_formula: 'NH₃', product_name: '암모니아', reaction_type: 'gas', animation: 'bubble', color: '#C8F0C8' },
  { elements: ["Ga", "As"], ratios: [1, 1], product_formula: 'GaAs', product_name: '비화갈륨(반도체)', reaction_type: 'combustion', animation: 'burn', color: '#808080' },
  { elements: ["Mg", "Si", "O"], ratios: [2, 1, 4], product_formula: 'Mg₂SiO₄', product_name: '감람석', reaction_type: 'precipitation', animation: 'sink', color: '#8B8B00' },
  { elements: ["Cd", "C", "O"], ratios: [1, 1, 3], product_formula: 'CdCO₃', product_name: '탄산카드뮴', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Hg", "Cl"], ratios: [2, 2], product_formula: 'Hg₂Cl₂', product_name: '염화수은(I)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Li", "Cl"], ratios: [1, 1], product_formula: 'LiCl', product_name: '염화리튬', reaction_type: 'dissolution', animation: 'colorchange', color: '#D0E8FF' },
  { elements: ["K", "I"], ratios: [1, 1], product_formula: 'KI', product_name: '아이오딘화칼륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Sr", "Cl"], ratios: [1, 2], product_formula: 'SrCl₂', product_name: '염화스트론튬', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["C", "H", "O"], ratios: [3, 6, 1], product_formula: 'C₂H₅CHO', product_name: '프로판알', reaction_type: 'dissolution', animation: 'dissolve', color: '#E0E0E0' },
  { elements: ["Na", "C", "N"], ratios: [1, 1, 1], product_formula: 'NaCN', product_name: '사이안화나트륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["C", "H"], ratios: [10, 22], product_formula: 'C₁₀H₂₂', product_name: '데케인', reaction_type: 'combustion', animation: 'burn', color: '#E0E0E0' },
  { elements: ["C", "H"], ratios: [8, 10], product_formula: 'C₈H₁₀', product_name: '자일렌', reaction_type: 'combustion', animation: 'burn', color: '#E0E0E0' },
  { elements: ["Pb", "O"], ratios: [1, 1], product_formula: 'PbO', product_name: '산화납(II)', reaction_type: 'precipitation', animation: 'sink', color: '#FFD700' },
  { elements: ["Al", "Cu"], ratios: [2, 1], product_formula: 'Al₂Cu', product_name: '금속간화합물 Al₂Cu', reaction_type: 'combustion', animation: 'burn', color: '#DAA520' },
  { elements: ["Ba", "C", "O"], ratios: [1, 1, 3], product_formula: 'BaCO₃', product_name: '탄산바륨', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["C", "H"], ratios: [8, 18], product_formula: 'C₈H₁₈', product_name: '옥테인(가솔린)', reaction_type: 'combustion', animation: 'burn', color: '#E0E0E0' },
  { elements: ["I", "O"], ratios: [2, 5], product_formula: 'I₂O₅', product_name: '오산화이아이오딘', reaction_type: 'precipitation', animation: 'sink', color: '#F0F0F0' },
  { elements: ["C", "H"], ratios: [7, 8], product_formula: 'C₇H₈', product_name: '톨루엔', reaction_type: 'combustion', animation: 'burn', color: '#E0E0E0' },
  { elements: ["Na", "C", "H", "O"], ratios: [1, 2, 3, 2], product_formula: 'CH₃COONa', product_name: '아세트산나트륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Ca", "C"], ratios: [1, 2], product_formula: 'CaC₂', product_name: '탄화칼슘(카바이드)', reaction_type: 'gas', animation: 'bubble', color: '#808080' },
  { elements: ["Cu", "N"], ratios: [3, 2], product_formula: 'Cu₃N₂', product_name: '질화구리', reaction_type: 'combustion', animation: 'burn', color: '#1A1A1A' },
  { elements: ["Na", "Br"], ratios: [1, 1], product_formula: 'NaBr', product_name: '브롬화나트륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Sr", "S", "O"], ratios: [1, 1, 4], product_formula: 'SrSO₄', product_name: '황산스트론튬', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["H", "Si", "O"], ratios: [2, 1, 3], product_formula: 'H₂SiO₃', product_name: '규산', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["C", "H"], ratios: [16, 34], product_formula: 'C₁₆H₃₄', product_name: '세테인(디젤)', reaction_type: 'combustion', animation: 'burn', color: '#F5DEB3' },
  { elements: ["C", "H", "O"], ratios: [5, 10, 5], product_formula: 'C₅H₁₀O₅', product_name: '리보스', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["Fe", "N"], ratios: [4, 1], product_formula: 'Fe₄N', product_name: '질화철', reaction_type: 'combustion', animation: 'burn', color: '#808080' },
  { elements: ["Pb", "C", "O"], ratios: [1, 1, 3], product_formula: 'PbCO₃', product_name: '탄산납', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Al", "C"], ratios: [4, 3], product_formula: 'Al₄C₃', product_name: '탄화알루미늄', reaction_type: 'gas', animation: 'bubble', color: '#F5F5DC' },
  { elements: ["Ba", "F"], ratios: [1, 2], product_formula: 'BaF₂', product_name: '플루오린화바륨', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Cr", "O"], ratios: [1, 3], product_formula: 'Cr₂O₃', product_name: '산화크롬(III)', reaction_type: 'color_change', animation: 'colorchange', color: '#228B22' },
  { elements: ["Mg", "Cl"], ratios: [1, 2], product_formula: 'MgCl₂', product_name: '염화마그네슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Cu", "Cl"], ratios: [1, 1], product_formula: 'CuCl', product_name: '염화구리(I)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5DC' },
  { elements: ["C", "O"], ratios: [1, 1], product_formula: 'CO', product_name: '일산화탄소', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["Co", "Cl"], ratios: [1, 2], product_formula: 'CoCl₂', product_name: '염화코발트(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#FF69B4' },
  { elements: ["Pb", "I"], ratios: [1, 2], product_formula: 'PbI₂', product_name: '요오드화납', reaction_type: 'precipitation', animation: 'sink', color: '#FFD700' },
  { elements: ["K", "N", "O"], ratios: [1, 1, 3], product_formula: 'KNO₃', product_name: '초석(화약)', reaction_type: 'explosion', animation: 'explode', color: '#FF8C00' },
  { elements: ["C", "H", "N", "O"], ratios: [12, 22, 2, 2], product_formula: 'C₁₂H₂₂N₂O₂', product_name: '나일론-6,6(단위)', reaction_type: 'none', animation: 'none', color: '#F5F5F5' },
  { elements: ["K", "Cr", "S", "O"], ratios: [1, 1, 2, 8], product_formula: 'KCr(SO₄)₂·12H₂O', product_name: '크롬백반', reaction_type: 'dissolution', animation: 'colorchange', color: '#4B0082' },
  { elements: ["Pb", "S", "O"], ratios: [1, 1, 4], product_formula: 'PbSO₄', product_name: '황산납', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Fe", "Ni"], ratios: [1, 1], product_formula: 'FeNi', product_name: '인바(불변강)', reaction_type: 'combustion', animation: 'burn', color: '#808080' },
  { elements: ["Sr", "C", "O"], ratios: [1, 1, 3], product_formula: 'SrCO₃', product_name: '탄산스트론튬', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["C", "H", "O"], ratios: [3, 6, 2], product_formula: 'CH₃COOCH₃', product_name: '아세트산메틸', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["Zn", "N"], ratios: [3, 2], product_formula: 'Zn₃N₂', product_name: '질화아연', reaction_type: 'combustion', animation: 'burn', color: '#808080' },
  { elements: ["Cu", "S", "O", "H"], ratios: [1, 1, 4, 2], product_formula: 'CuSO₄·(OH)₂', product_name: '염기성황산구리', reaction_type: 'precipitation', animation: 'sink', color: '#1E90FF' },
  { elements: ["K", "O"], ratios: [2, 1], product_formula: 'K₂O', product_name: '산화칼륨', reaction_type: 'combustion', animation: 'burn', color: '#F0F0F0' },
  { elements: ["Ca", "S", "O"], ratios: [1, 1, 4], product_formula: 'CaSO₄', product_name: '황산칼슘(석고)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Ag", "O", "H"], ratios: [1, 1, 1], product_formula: 'AgOH', product_name: '수산화은', reaction_type: 'precipitation', animation: 'sink', color: '#E0E0E0' },
  { elements: ["C", "H", "O"], ratios: [6, 12, 2], product_formula: 'C₆H₁₂O₂', product_name: '카프로산', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["Rb", "Cl"], ratios: [1, 1], product_formula: 'RbCl', product_name: '염화루비듐', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Pb", "C", "H", "O"], ratios: [1, 4, 6, 4], product_formula: '(CH₃COO)₂Pb', product_name: '아세트산납', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5DC' },
  { elements: ["Ag", "N", "O"], ratios: [1, 1, 3], product_formula: 'AgNO₃', product_name: '질산은', reaction_type: 'dissolution', animation: 'colorchange', color: '#D0E8FF' },
  { elements: ["Mg", "C"], ratios: [2, 1], product_formula: 'MgC', product_name: '탄화마그네슘', reaction_type: 'gas', animation: 'bubble', color: '#F5F5F5' },
  { elements: ["Ga", "N"], ratios: [1, 1], product_formula: 'GaN', product_name: '질화갈륨', reaction_type: 'combustion', animation: 'burn', color: '#F5F5DC' },
  { elements: ["Sn", "O"], ratios: [1, 1], product_formula: 'SnO', product_name: '산화주석(II)', reaction_type: 'precipitation', animation: 'sink', color: '#404040' },
  { elements: ["C", "H", "O"], ratios: [12, 22, 11], product_formula: 'C₁₂H₂₂O₁₁', product_name: '락토스(유당)', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["N", "O"], ratios: [1, 2], product_formula: 'NO₂', product_name: '이산화질소', reaction_type: 'gas', animation: 'bubble', color: '#FF8C00' },
  { elements: ["N", "O"], ratios: [2, 3], product_formula: 'N₂O₃', product_name: '삼산화이질소', reaction_type: 'gas', animation: 'bubble', color: '#87CEEB' },
  { elements: ["N", "H", "O"], ratios: [1, 3, 1], product_formula: 'NH₄OH', product_name: '암모니아수', reaction_type: 'gas', animation: 'bubble', color: '#D0E8FF' },
  { elements: ["Co", "S", "O"], ratios: [1, 1, 4], product_formula: 'CoSO₄', product_name: '황산코발트(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#FF4500' },
  { elements: ["Ti", "C"], ratios: [1, 1], product_formula: 'TiC', product_name: '탄화타이타늄', reaction_type: 'combustion', animation: 'burn', color: '#2F2F2F' },
  { elements: ["Na", "N"], ratios: [1, 3], product_formula: 'NaN₃', product_name: '아지드화나트륨', reaction_type: 'explosion', animation: 'explode', color: '#F5F5F5' },
  { elements: ["C", "H"], ratios: [2, 4], product_formula: 'C₂H₄', product_name: '에틸렌(에텐)', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["Rb", "O"], ratios: [2, 1], product_formula: 'Rb₂O', product_name: '산화루비듐', reaction_type: 'combustion', animation: 'burn', color: '#F0F0F0' },
  { elements: ["Pb", "I"], ratios: [1, 2], product_formula: 'PbI₂', product_name: '아이오딘화납(중복방지)', reaction_type: 'precipitation', animation: 'sink', color: '#FFD700' },
  { elements: ["Ca", "O"], ratios: [1, 1], product_formula: 'CaO', product_name: '산화칼슘', reaction_type: 'combustion', animation: 'burn', color: '#FFFFFF' },
  { elements: ["Pb", "Br"], ratios: [1, 2], product_formula: 'PbBr₂', product_name: '브롬화납', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["K", "F"], ratios: [1, 1], product_formula: 'KF', product_name: '플루오린화칼륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Li", "Mn", "O"], ratios: [1, 2, 4], product_formula: 'LiMn₂O₄', product_name: '리튬망간산화물(배터리)', reaction_type: 'dissolution', animation: 'colorchange', color: '#2F2F2F' },
  { elements: ["C", "H", "O"], ratios: [9, 8, 4], product_formula: 'C₉H₈O₄', product_name: '아스피린', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["K", "O", "H"], ratios: [1, 1, 1], product_formula: 'KOH', product_name: '수산화칼륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["H", "S", "O"], ratios: [2, 1, 3], product_formula: 'H₂SO₃', product_name: '아황산', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Li", "Fe", "P", "O"], ratios: [1, 1, 1, 4], product_formula: 'LiFePO₄', product_name: '인산철리튬(LFP)', reaction_type: 'dissolution', animation: 'colorchange', color: '#556B2F' },
  { elements: ["H", "B", "O"], ratios: [3, 1, 3], product_formula: 'H₃BO₃', product_name: '붕산', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["C", "H", "O"], ratios: [4, 8, 2], product_formula: 'CH₃COOC₂H₅', product_name: '아세트산에틸(과일향)', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["Zn", "O"], ratios: [1, 1], product_formula: 'ZnO', product_name: '산화아연', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["H", "N", "O"], ratios: [1, 1, 2], product_formula: 'HNO₂', product_name: '아질산', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["W", "C"], ratios: [1, 1], product_formula: 'WC', product_name: '탄화텅스텐', reaction_type: 'combustion', animation: 'burn', color: '#2F2F2F' },
  { elements: ["Ag", "Cu"], ratios: [1, 1], product_formula: 'AgCu', product_name: '은구리 공정합금', reaction_type: 'combustion', animation: 'burn', color: '#C0C0C0' },
  { elements: ["Li", "C", "O"], ratios: [2, 1, 3], product_formula: 'Li₂CO₃', product_name: '탄산리튬', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Mg", "O"], ratios: [1, 2], product_formula: 'MgO₂', product_name: '과산화마그네슘', reaction_type: 'explosion', animation: 'explode', color: '#F5F5F5' },
  { elements: ["Cs", "O", "H"], ratios: [1, 1, 1], product_formula: 'CsOH', product_name: '수산화세슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Bi", "N", "O"], ratios: [1, 3, 9], product_formula: 'Bi(NO₃)₃', product_name: '질산비스무트', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Na", "I"], ratios: [1, 1], product_formula: 'NaI', product_name: '아이오딘화나트륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Bi", "O", "H"], ratios: [1, 3, 3], product_formula: 'Bi(OH)₃', product_name: '수산화비스무트', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5DC' },
  { elements: ["C", "H", "N", "O"], ratios: [8, 10, 4, 2], product_formula: 'C₈H₁₀N₄O₂', product_name: '카페인', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5DC' },
  { elements: ["C", "H", "O"], ratios: [16, 32, 2], product_formula: 'C₁₆H₃₂O₂', product_name: '팔미트산', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5DC' },
  { elements: ["Ni", "O", "H"], ratios: [1, 2, 2], product_formula: 'Ni(OH)₂', product_name: '수산화니켈(II)', reaction_type: 'precipitation', animation: 'sink', color: '#4CAF50' },
  { elements: ["K", "O"], ratios: [1, 2], product_formula: 'KO₂', product_name: '초산화칼륨', reaction_type: 'explosion', animation: 'explode', color: '#F5E8C0' },
  { elements: ["Cu", "In", "Se"], ratios: [1, 1, 2], product_formula: 'CuInSe₂', product_name: '황동광형 태양전지', reaction_type: 'combustion', animation: 'burn', color: '#8B4513' },
  { elements: ["Fe", "Br"], ratios: [1, 3], product_formula: 'FeBr₃', product_name: '브롬화철(III)', reaction_type: 'dissolution', animation: 'colorchange', color: '#8B4513' },
  { elements: ["Cu", "N", "O"], ratios: [1, 2, 6], product_formula: 'Cu(NO₃)₂', product_name: '질산구리(청록불꽃)', reaction_type: 'combustion', animation: 'burn', color: '#00CED1' },
  { elements: ["Cr", "S"], ratios: [1, 1], product_formula: 'CrS', product_name: '황화크롬', reaction_type: 'precipitation', animation: 'sink', color: '#2F2F2F' },
  { elements: ["Sn", "Cl"], ratios: [1, 2], product_formula: 'SnCl₂', product_name: '염화주석(II)', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["C", "H", "O"], ratios: [2, 4, 2], product_formula: 'C₂H₄O₂', product_name: '에틸폼산', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["H", "S", "O"], ratios: [2, 1, 4], product_formula: 'H₂SO₄', product_name: '황산', reaction_type: 'dissolution', animation: 'colorchange', color: '#D8D8D8' },
  { elements: ["Ca", "Mg", "Si", "O"], ratios: [1, 1, 2, 6], product_formula: 'CaMgSi₂O₆', product_name: '투휘석', reaction_type: 'precipitation', animation: 'sink', color: '#556B2F' },
  { elements: ["Cl", "O"], ratios: [1, 2], product_formula: 'ClO₂', product_name: '이산화염소', reaction_type: 'gas', animation: 'bubble', color: '#F5D060' },
  { elements: ["C", "H", "N", "O"], ratios: [21, 23, 1, 5], product_formula: 'C₂₁H₂₃NO₅', product_name: '모르핀', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5DC' },
  { elements: ["H", "F"], ratios: [1, 1], product_formula: 'HF', product_name: '플루오린화수소(불산)', reaction_type: 'gas', animation: 'bubble', color: '#E8F5E9' },
  { elements: ["Zn", "Br"], ratios: [1, 2], product_formula: 'ZnBr₂', product_name: '브롬화아연', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Fe", "C", "H", "O"], ratios: [1, 6, 9, 6], product_formula: 'Fe(CH₃COO)₃', product_name: '아세트산철(III)', reaction_type: 'dissolution', animation: 'colorchange', color: '#8B4513' },
  { elements: ["S", "O"], ratios: [1, 2], product_formula: 'SO₂', product_name: '이산화황', reaction_type: 'gas', animation: 'bubble', color: '#FFFF99' },
  { elements: ["Fe", "O", "H"], ratios: [1, 3, 3], product_formula: 'Fe(OH)₃', product_name: '수산화철(III)', reaction_type: 'precipitation', animation: 'sink', color: '#8B4513' },
  { elements: ["Zn", "S"], ratios: [1, 1], product_formula: 'ZnS', product_name: '황화아연', reaction_type: 'precipitation', animation: 'sink', color: '#FFFACD' },
  { elements: ["C", "H", "O"], ratios: [2, 2, 4], product_formula: 'C₂H₂O₄', product_name: '옥살산', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["Zn", "P", "O"], ratios: [3, 2, 8], product_formula: 'Zn₃(PO₄)₂', product_name: '인산아연', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Ag", "S"], ratios: [2, 1], product_formula: 'Ag₂S', product_name: '황화은', reaction_type: 'precipitation', animation: 'sink', color: '#1A1A1A' },
  { elements: ["Na", "O", "H"], ratios: [1, 1, 1], product_formula: 'NaOH', product_name: '수산화나트륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Ti", "N"], ratios: [1, 1], product_formula: 'TiN', product_name: '질화타이타늄', reaction_type: 'combustion', animation: 'burn', color: '#FFD700' },
  { elements: ["Mn", "S", "O"], ratios: [1, 1, 4], product_formula: 'MnSO₄', product_name: '황산망간(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#FFB6C1' },
  { elements: ["Al", "F"], ratios: [1, 3], product_formula: 'AlF₃', product_name: '플루오린화알루미늄', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Sn", "O", "H"], ratios: [1, 4, 4], product_formula: 'Sn(OH)₄', product_name: '수산화주석(IV)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["N", "H", "Br"], ratios: [1, 4, 1], product_formula: 'NH₄Br', product_name: '브롬화암모늄', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Ba", "S", "O"], ratios: [1, 1, 4], product_formula: 'BaSO₄', product_name: '황산바륨', reaction_type: 'precipitation', animation: 'sink', color: '#FFFFFF' },
  { elements: ["K", "H", "C", "O"], ratios: [1, 1, 1, 3], product_formula: 'KHCO₃', product_name: '탄산수소칼륨', reaction_type: 'gas', animation: 'bubble', color: '#F5F5F5' },
  { elements: ["Ba", "O"], ratios: [1, 1], product_formula: 'BaO', product_name: '산화바륨', reaction_type: 'combustion', animation: 'burn', color: '#F5F5F5' },
  { elements: ["Ni", "S"], ratios: [1, 1], product_formula: 'NiS', product_name: '황화니켈', reaction_type: 'precipitation', animation: 'sink', color: '#1A1A1A' },
  { elements: ["Cr", "S", "O"], ratios: [2, 3, 12], product_formula: 'Cr₂(SO₄)₃', product_name: '황산크롬(III)', reaction_type: 'dissolution', animation: 'colorchange', color: '#4B0082' },
  { elements: ["Co", "O"], ratios: [1, 1], product_formula: 'CoO', product_name: '산화코발트(II)', reaction_type: 'precipitation', animation: 'sink', color: '#808080' },
  { elements: ["In", "Ga", "N"], ratios: [1, 1, 1], product_formula: 'InGaN', product_name: '질화인듐갈륨(LED)', reaction_type: 'combustion', animation: 'burn', color: '#00BFFF' },
  { elements: ["Pb", "S"], ratios: [1, 1], product_formula: 'PbS', product_name: '황화납', reaction_type: 'precipitation', animation: 'sink', color: '#2F2F2F' },
  { elements: ["Ca", "F"], ratios: [1, 2], product_formula: 'CaF₂', product_name: '형석(fluorite)', reaction_type: 'precipitation', animation: 'sink', color: '#9370DB' },
  { elements: ["Pb", "P", "O"], ratios: [3, 2, 8], product_formula: 'Pb₃(PO₄)₂', product_name: '인산납', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5DC' },
  { elements: ["Na", "Mn", "O"], ratios: [1, 1, 4], product_formula: 'NaMnO₄', product_name: '과망간산나트륨', reaction_type: 'color_change', animation: 'colorchange', color: '#8B008B' },
  { elements: ["Ca", "Si", "O"], ratios: [1, 1, 3], product_formula: 'CaSiO₃', product_name: '규산칼슘(규회석)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Sr", "N", "O"], ratios: [1, 2, 6], product_formula: 'Sr(NO₃)₂', product_name: '질산스트론튬(적색불꽃)', reaction_type: 'combustion', animation: 'burn', color: '#FF0000' },
  { elements: ["Fe", "O"], ratios: [2, 3], product_formula: 'Fe₂O₃', product_name: '산화철(III)', reaction_type: 'precipitation', animation: 'sink', color: '#8B4513' },
  { elements: ["N", "H"], ratios: [2, 4], product_formula: 'N₂H₄', product_name: '하이드라진(로켓)', reaction_type: 'explosion', animation: 'explode', color: '#FF4500' },
  { elements: ["Cu", "C", "H", "O"], ratios: [1, 4, 6, 4], product_formula: '(CH₃COO)₂Cu', product_name: '아세트산구리', reaction_type: 'dissolution', animation: 'colorchange', color: '#228B22' },
  { elements: ["Na", "S", "O"], ratios: [2, 1, 4], product_formula: 'Na₂SO₄', product_name: '황산나트륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["C", "H"], ratios: [10, 8], product_formula: 'C₁₀H₈', product_name: '나프탈렌', reaction_type: 'combustion', animation: 'burn', color: '#F5F5F5' },
  { elements: ["Ni", "N", "O"], ratios: [1, 2, 6], product_formula: 'Ni(NO₃)₂', product_name: '질산니켈(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#90EE90' },
  { elements: ["Ti", "O"], ratios: [1, 2], product_formula: 'TiO₂', product_name: '이산화타이타늄', reaction_type: 'combustion', animation: 'burn', color: '#FFFFFF' },
  { elements: ["Ca", "Al", "Si", "O"], ratios: [1, 2, 2, 8], product_formula: 'CaAl₂Si₂O₈', product_name: '회장석', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["As", "S"], ratios: [2, 3], product_formula: 'As₂S₃', product_name: '황화비소(III)', reaction_type: 'precipitation', animation: 'sink', color: '#FFD700' },
  { elements: ["C", "H"], ratios: [5, 12], product_formula: 'C₅H₁₂', product_name: '펜테인', reaction_type: 'combustion', animation: 'burn', color: '#E0E0E0' },
  { elements: ["C", "H", "N", "O", "S"], ratios: [16, 18, 2, 5, 1], product_formula: 'C₁₆H₁₈N₂O₅S', product_name: '페니실린G', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5DC' },
  { elements: ["Fe", "N", "O"], ratios: [1, 2, 6], product_formula: 'Fe(NO₃)₂', product_name: '질산철(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#6B8E23' },
  { elements: ["Li", "O"], ratios: [2, 1], product_formula: 'Li₂O', product_name: '산화리튬', reaction_type: 'combustion', animation: 'burn', color: '#F5F5F5' },
  { elements: ["Ca", "N"], ratios: [3, 2], product_formula: 'Ca₃N₂', product_name: '질화칼슘', reaction_type: 'combustion', animation: 'burn', color: '#F5F0E0' },
  { elements: ["C", "H", "N"], ratios: [1, 5, 1], product_formula: 'CH₅N', product_name: '메틸아민', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["Cu", "O"], ratios: [1, 1], product_formula: 'CuO', product_name: '산화구리(II)', reaction_type: 'precipitation', animation: 'sink', color: '#1A1A1A' },
  { elements: ["Cu", "C", "O"], ratios: [1, 1, 3], product_formula: 'CuCO₃', product_name: '탄산구리(II)', reaction_type: 'precipitation', animation: 'sink', color: '#4169E1' },
  { elements: ["Mg", "P", "O"], ratios: [3, 2, 8], product_formula: 'Mg₃(PO₄)₂', product_name: '인산마그네슘', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Na", "H", "P", "O"], ratios: [1, 2, 1, 4], product_formula: 'NaH₂PO₄', product_name: '인산이수소나트륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Cs", "Cl"], ratios: [1, 1], product_formula: 'CsCl', product_name: '염화세슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["C", "H", "F"], ratios: [1, 2, 2], product_formula: 'CH₂F₂', product_name: '다이플루오로메테인', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["N", "O"], ratios: [1, 1], product_formula: 'NO', product_name: '일산화질소', reaction_type: 'gas', animation: 'bubble', color: '#D0D0D0' },
  { elements: ["Al", "S", "O"], ratios: [2, 3, 12], product_formula: 'Al₂(SO₄)₃', product_name: '황산알루미늄', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Na", "H", "C", "O"], ratios: [1, 1, 1, 3], product_formula: 'NaHCO₃', product_name: '탄산수소나트륨', reaction_type: 'gas', animation: 'bubble', color: '#F5F5F5' },
  { elements: ["V", "O"], ratios: [2, 5], product_formula: 'V₂O₅', product_name: '오산화이바나듐', reaction_type: 'combustion', animation: 'burn', color: '#FF8C00' },
  { elements: ["Mo", "O"], ratios: [1, 3], product_formula: 'MoO₃', product_name: '삼산화몰리브덴', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Mg", "S"], ratios: [1, 1], product_formula: 'MgS', product_name: '황화마그네슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5DC' },
  { elements: ["Mg", "N", "O"], ratios: [1, 2, 6], product_formula: 'Mg(NO₃)₂', product_name: '질산마그네슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Tl", "S"], ratios: [2, 1], product_formula: 'Tl₂S', product_name: '황화탈륨', reaction_type: 'precipitation', animation: 'sink', color: '#1A1A1A' },
  { elements: ["C", "H"], ratios: [3, 6], product_formula: 'C₃H₆', product_name: '프로필렌(프로펜)', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["Cr", "O", "H"], ratios: [1, 3, 3], product_formula: 'Cr(OH)₃', product_name: '수산화크롬(III)', reaction_type: 'precipitation', animation: 'sink', color: '#808000' },
  { elements: ["Hg", "I"], ratios: [1, 2], product_formula: 'HgI₂', product_name: '아이오딘화수은(II)', reaction_type: 'precipitation', animation: 'sink', color: '#FF0000' },
  { elements: ["B", "O"], ratios: [2, 3], product_formula: 'B₂O₃', product_name: '삼산화붕소', reaction_type: 'gas', animation: 'bubble', color: '#F5F5F5' },
  { elements: ["Cu", "O"], ratios: [2, 1], product_formula: 'Cu₂O', product_name: '산화구리(I)', reaction_type: 'precipitation', animation: 'sink', color: '#8B2500' },
  { elements: ["Sn", "Cl"], ratios: [1, 4], product_formula: 'SnCl₄', product_name: '염화주석(IV)', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["C", "H", "O"], ratios: [6, 8, 7], product_formula: 'C₆H₈O₇', product_name: '시트르산', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5DC' },
  { elements: ["Fe", "N", "O"], ratios: [1, 3, 9], product_formula: 'Fe(NO₃)₃', product_name: '질산철(III)', reaction_type: 'dissolution', animation: 'colorchange', color: '#FF8C00' },
  { elements: ["Pb", "N", "O"], ratios: [1, 2, 6], product_formula: 'Pb(NO₃)₂', product_name: '질산납', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Fe", "S"], ratios: [1, 2], product_formula: 'FeS₂', product_name: '황철광(pyrite)', reaction_type: 'precipitation', animation: 'sink', color: '#DAA520' },
  { elements: ["Cd", "Cl"], ratios: [1, 2], product_formula: 'CdCl₂', product_name: '염화카드뮴', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["H", "P", "O"], ratios: [3, 1, 3], product_formula: 'H₃PO₃', product_name: '아인산', reaction_type: 'dissolution', animation: 'dissolve', color: '#E8F0FF' },
  { elements: ["Hg", "O"], ratios: [2, 1], product_formula: 'Hg₂O', product_name: '산화수은(I)', reaction_type: 'precipitation', animation: 'sink', color: '#1A1A1A' },
  { elements: ["Ca", "H", "C", "O"], ratios: [1, 2, 2, 6], product_formula: 'Ca(HCO₃)₂', product_name: '탄산수소칼슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Al", "N", "O"], ratios: [1, 3, 9], product_formula: 'Al(NO₃)₃', product_name: '질산알루미늄', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["K", "S"], ratios: [2, 1], product_formula: 'K₂S', product_name: '황화칼륨', reaction_type: 'dissolution', animation: 'colorchange', color: '#F5F5DC' },
  { elements: ["C", "H", "O"], ratios: [3, 8, 1], product_formula: 'C₃H₇OH', product_name: '프로판올', reaction_type: 'combustion', animation: 'burn', color: '#ADD8E6' },
  { elements: ["C", "H", "Cl"], ratios: [1, 2, 2], product_formula: 'CH₂Cl₂', product_name: '다이클로로메테인', reaction_type: 'dissolution', animation: 'dissolve', color: '#E0E0E0' },
  { elements: ["Ga", "P"], ratios: [1, 1], product_formula: 'GaP', product_name: '인화갈륨(LED)', reaction_type: 'combustion', animation: 'burn', color: '#FF4500' },
  { elements: ["C", "H"], ratios: [3, 4], product_formula: 'C₃H₄', product_name: '프로파인', reaction_type: 'combustion', animation: 'burn', color: '#E0E0E0' },
  { elements: ["C", "H", "O"], ratios: [2, 6, 2], product_formula: 'C₂H₆O₂', product_name: '에틸렌글리콜', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["Li", "F"], ratios: [1, 1], product_formula: 'LiF', product_name: '플루오린화리튬', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["C", "H", "Br"], ratios: [1, 3, 1], product_formula: 'CH₃Br', product_name: '브로모메테인', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["Ti", "Al"], ratios: [1, 1], product_formula: 'TiAl', product_name: '티탄알루미나이드', reaction_type: 'combustion', animation: 'burn', color: '#C0C0C0' },
  { elements: ["N", "O"], ratios: [2, 5], product_formula: 'N₂O₅', product_name: '오산화이질소', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["Fe", "S", "O"], ratios: [1, 1, 4], product_formula: 'FeSO₄', product_name: '황산철(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#7CFC00' },
  { elements: ["Sb", "S"], ratios: [2, 3], product_formula: 'Sb₂S₃', product_name: '황화안티모니', reaction_type: 'precipitation', animation: 'sink', color: '#FF4500' },
  { elements: ["Mn", "O", "H"], ratios: [1, 2, 2], product_formula: 'Mn(OH)₂', product_name: '수산화망간(II)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5DC' },
  { elements: ["Bi", "Cl"], ratios: [1, 3], product_formula: 'BiCl₃', product_name: '염화비스무트', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Be", "O", "H"], ratios: [1, 2, 2], product_formula: 'Be(OH)₂', product_name: '수산화베릴륨', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["K", "N", "O"], ratios: [1, 1, 3], product_formula: 'KNO₃', product_name: '질산칼륨(초석)', reaction_type: 'explosion', animation: 'explode', color: '#FF8C00' },
  { elements: ["C", "H", "O"], ratios: [4, 6, 4], product_formula: 'C₄H₆O₄', product_name: '석신산', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["Mg", "Br"], ratios: [1, 2], product_formula: 'MgBr₂', product_name: '브롬화마그네슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Al", "N"], ratios: [1, 1], product_formula: 'AlN', product_name: '질화알루미늄', reaction_type: 'combustion', animation: 'burn', color: '#F5F5F5' },
  { elements: ["Hg", "O"], ratios: [1, 1], product_formula: 'HgO', product_name: '산화수은(II)', reaction_type: 'precipitation', animation: 'sink', color: '#FF0000' },
  { elements: ["Ba", "N", "O"], ratios: [1, 2, 6], product_formula: 'Ba(NO₃)₂', product_name: '질산바륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["C", "H", "O"], ratios: [3, 6, 1], product_formula: 'CH₃COCH₃', product_name: '아세톤', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["Hg", "Br"], ratios: [1, 2], product_formula: 'HgBr₂', product_name: '브롬화수은(II)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5DC' },
  { elements: ["Ca", "H", "P", "O"], ratios: [1, 2, 2, 8], product_formula: 'Ca(H₂PO₄)₂', product_name: '과인산석회(비료)', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["K", "C", "O"], ratios: [2, 1, 3], product_formula: 'K₂CO₃', product_name: '탄산칼륨(재)', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Cd", "Te"], ratios: [1, 1], product_formula: 'CdTe', product_name: '텔루르화카드뮴(태양전지)', reaction_type: 'combustion', animation: 'burn', color: '#2F2F2F' },
  { elements: ["H", "P", "O"], ratios: [3, 1, 4], product_formula: 'H₃PO₄', product_name: '인산', reaction_type: 'dissolution', animation: 'dissolve', color: '#E8F0FF' },
  { elements: ["Mg", "N"], ratios: [3, 2], product_formula: 'Mg₃N₂', product_name: '질화마그네슘', reaction_type: 'combustion', animation: 'burn', color: '#F5E0C0' },
  { elements: ["K", "Cl"], ratios: [1, 1], product_formula: 'KCl', product_name: '염화칼륨(비료)', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5E8E8' },
  { elements: ["Cu", "F"], ratios: [1, 2], product_formula: 'CuF₂', product_name: '플루오린화구리', reaction_type: 'dissolution', animation: 'colorchange', color: '#87CEEB' },
  { elements: ["Mn", "O"], ratios: [1, 2], product_formula: 'MnO₂', product_name: '이산화망간', reaction_type: 'precipitation', animation: 'sink', color: '#2F2F2F' },
  { elements: ["Ca", "C", "O"], ratios: [1, 1, 3], product_formula: 'CaCO₃', product_name: '탄산칼슘', reaction_type: 'precipitation', animation: 'sink', color: '#F0F0F0' },
  { elements: ["Ca", "N", "O"], ratios: [1, 2, 6], product_formula: 'Ca(NO₃)₂', product_name: '질산칼슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Al", "Si", "O"], ratios: [2, 2, 5], product_formula: 'Al₂Si₂O₅', product_name: '카올리나이트(도자기)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["H", "Mn", "O"], ratios: [1, 1, 4], product_formula: 'HMnO₄', product_name: '과망간산', reaction_type: 'color_change', animation: 'colorchange', color: '#8B008B' },
  { elements: ["C", "H", "O"], ratios: [12, 22, 11], product_formula: 'C₁₂H₂₂O₁₁', product_name: '설탕(수크로스)', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["H", "Cl"], ratios: [1, 1], product_formula: 'HCl', product_name: '염화수소', reaction_type: 'gas', animation: 'bubble', color: '#E8E8FF' },
  { elements: ["C", "H", "O"], ratios: [1, 2, 1], product_formula: 'HCHO', product_name: '폼알데히드', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["C", "H", "O"], ratios: [18, 34, 2], product_formula: 'C₁₈H₃₄O₂', product_name: '올레산', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5DC' },
  { elements: ["B", "N"], ratios: [1, 1], product_formula: 'BN', product_name: '질화붕소', reaction_type: 'combustion', animation: 'burn', color: '#F5F5F5' },
  { elements: ["Cd", "O", "H"], ratios: [1, 2, 2], product_formula: 'Cd(OH)₂', product_name: '수산화카드뮴(NiCd)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5DC' },
  { elements: ["Fe", "O"], ratios: [3, 4], product_formula: 'Fe₃O₄', product_name: '자철광(magnetite)', reaction_type: 'precipitation', animation: 'sink', color: '#1A1A1A' },
  { elements: ["Be", "O"], ratios: [1, 1], product_formula: 'BeO', product_name: '산화베릴륨', reaction_type: 'combustion', animation: 'burn', color: '#FFFFFF' },
  { elements: ["Co", "S"], ratios: [1, 1], product_formula: 'CoS', product_name: '황화코발트', reaction_type: 'precipitation', animation: 'sink', color: '#1A1A1A' },
  { elements: ["Ba", "Cl"], ratios: [1, 2], product_formula: 'BaCl₂', product_name: '염화바륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Mg", "O"], ratios: [2, 1], product_formula: 'MgO', product_name: '산화마그네슘', reaction_type: 'combustion', animation: 'burn', color: '#FFFFFF' },
  { elements: ["N", "H", "S", "O"], ratios: [2, 8, 1, 4], product_formula: '(NH₄)₂SO₄', product_name: '황산암모늄(비료)', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["C", "H", "N", "O"], ratios: [2, 5, 1, 2], product_formula: 'C₂H₅NO₂', product_name: '글리신', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["Cu", "S"], ratios: [2, 1], product_formula: 'Cu₂S', product_name: '휘동석', reaction_type: 'precipitation', animation: 'sink', color: '#1A1A1A' },
  { elements: ["C", "H", "O"], ratios: [2, 4, 1], product_formula: 'C₂H₄O', product_name: '산화에틸렌', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["Pb", "S"], ratios: [1, 1], product_formula: 'PbS', product_name: '방연석(galena)', reaction_type: 'precipitation', animation: 'sink', color: '#808080' },
  { elements: ["W", "O"], ratios: [1, 3], product_formula: 'WO₃', product_name: '삼산화텅스텐', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5DC' },
  { elements: ["H", "Cl", "O"], ratios: [1, 1, 3], product_formula: 'HClO₃', product_name: '염소산', reaction_type: 'dissolution', animation: 'dissolve', color: '#D8FFD8' },
  { elements: ["Cu", "S"], ratios: [2, 1], product_formula: 'Cu₂S', product_name: '황화구리(I)', reaction_type: 'precipitation', animation: 'sink', color: '#1A1A1A' },
  { elements: ["K", "Al", "Si", "O"], ratios: [1, 1, 3, 8], product_formula: 'KAlSi₃O₈', product_name: '정장석', reaction_type: 'precipitation', animation: 'sink', color: '#F5E8E0' },
  { elements: ["Ba", "O"], ratios: [1, 2], product_formula: 'BaO₂', product_name: '과산화바륨', reaction_type: 'explosion', animation: 'explode', color: '#F5F5F5' },
  { elements: ["H", "C", "N"], ratios: [1, 1, 1], product_formula: 'HCN', product_name: '사이안화수소', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["Cu", "Br"], ratios: [1, 2], product_formula: 'CuBr₂', product_name: '브롬화구리(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#4682B4' },
  { elements: ["N", "H", "C", "O"], ratios: [2, 8, 1, 3], product_formula: '(NH₄)₂CO₃', product_name: '탄산암모늄', reaction_type: 'gas', animation: 'bubble', color: '#D0E8FF' },
  { elements: ["Mn", "N", "O"], ratios: [1, 2, 6], product_formula: 'Mn(NO₃)₂', product_name: '질산망간(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#FFB6C1' },
  { elements: ["K", "P", "O"], ratios: [3, 1, 4], product_formula: 'K₃PO₄', product_name: '인산칼륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Na", "N", "O"], ratios: [1, 1, 3], product_formula: 'NaNO₃', product_name: '질산나트륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Ga", "S"], ratios: [2, 3], product_formula: 'Ga₂S₃', product_name: '황화갈륨', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5DC' },
  { elements: ["C", "H", "O"], ratios: [7, 6, 2], product_formula: 'C₇H₆O₂', product_name: '안식향산메틸', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5DC' },
  { elements: ["Ag", "I"], ratios: [1, 1], product_formula: 'AgI', product_name: '요오드화은', reaction_type: 'precipitation', animation: 'sink', color: '#F4D03F' },
  { elements: ["Sr", "O"], ratios: [1, 1], product_formula: 'SrO', product_name: '산화스트론튬', reaction_type: 'combustion', animation: 'burn', color: '#F5F5F5' },
  { elements: ["Cr", "Cl"], ratios: [1, 3], product_formula: 'CrCl₃', product_name: '염화크롬(III)', reaction_type: 'dissolution', animation: 'colorchange', color: '#4B0082' },
  { elements: ["K", "Mg", "Cl", "S", "O"], ratios: [1, 1, 3, 1, 4], product_formula: 'KMgCl₃SO₄', product_name: '광물염혼합', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5DC' },
  { elements: ["Ca", "Cl"], ratios: [1, 2], product_formula: 'CaCl₂', product_name: '염화칼슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["C", "H", "O"], ratios: [4, 8, 1], product_formula: 'C₄H₈O', product_name: '뷰탄온(MEK)', reaction_type: 'dissolution', animation: 'dissolve', color: '#E0E0E0' },
  { elements: ["Cd", "O", "H"], ratios: [1, 2, 2], product_formula: 'Cd(OH)₂', product_name: '수산화카드뮴', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Ca", "O"], ratios: [1, 2], product_formula: 'CaO₂', product_name: '과산화칼슘', reaction_type: 'explosion', animation: 'explode', color: '#F5F5F5' },
  { elements: ["Ca", "Mn", "O"], ratios: [1, 2, 8], product_formula: 'Ca(MnO₄)₂', product_name: '과망간산칼슘', reaction_type: 'color_change', animation: 'colorchange', color: '#8B008B' },
  { elements: ["Rb", "O", "H"], ratios: [1, 1, 1], product_formula: 'RbOH', product_name: '수산화루비듐', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Fe", "C", "O"], ratios: [1, 1, 3], product_formula: 'FeCO₃', product_name: '탄산철(II)', reaction_type: 'precipitation', animation: 'sink', color: '#808080' },
  { elements: ["Pt", "Al"], ratios: [1, 1], product_formula: 'PtAl', product_name: '백금알루미나이드', reaction_type: 'combustion', animation: 'burn', color: '#E0E0E0' },
  { elements: ["C", "H"], ratios: [2, 6], product_formula: 'C₂H₆', product_name: '에테인', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["Cu", "O", "H"], ratios: [1, 2, 2], product_formula: 'Cu(OH)₂', product_name: '수산화구리(II)', reaction_type: 'precipitation', animation: 'sink', color: '#4169E1' },
  { elements: ["C", "H", "O"], ratios: [12, 24, 2], product_formula: 'C₁₂H₂₄O₂', product_name: '라우르산', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["C", "H", "O"], ratios: [5, 10, 2], product_formula: 'CH₃COO(C₃H₇)', product_name: '아세트산아밀(바나나향)', reaction_type: 'dissolution', animation: 'dissolve', color: '#FFD700' },
  { elements: ["Ca", "O", "H"], ratios: [1, 2, 2], product_formula: 'Ca(OH)₂', product_name: '수산화칼슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["C", "H", "N", "O", "S"], ratios: [3, 7, 1, 2, 1], product_formula: 'C₃H₇NO₂S', product_name: '시스테인', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["Cd", "O"], ratios: [1, 1], product_formula: 'CdO', product_name: '산화카드뮴', reaction_type: 'precipitation', animation: 'sink', color: '#8B4513' },
  { elements: ["K", "Cl"], ratios: [1, 1], product_formula: 'KCl', product_name: '염화칼륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["H", "Cl", "O"], ratios: [1, 1, 2], product_formula: 'HClO₂', product_name: '아염소산', reaction_type: 'dissolution', animation: 'dissolve', color: '#E0FFE0' },
  { elements: ["Li", "O", "H"], ratios: [1, 1, 1], product_formula: 'LiOH', product_name: '수산화리튬', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Al", "N", "O"], ratios: [1, 3, 9], product_formula: 'Al(NO₃)₃', product_name: '질산알루미늄(백색불꽃)', reaction_type: 'combustion', animation: 'burn', color: '#FFFFFF' },
  { elements: ["Pb", "O", "H"], ratios: [1, 2, 2], product_formula: 'Pb(OH)₂', product_name: '수산화납', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["C", "H", "O"], ratios: [6, 12, 6], product_formula: 'C₆H₁₂O₆', product_name: '포도당(글루코스)', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["Ca", "I"], ratios: [1, 2], product_formula: 'CaI₂', product_name: '아이오딘화칼슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["In", "P"], ratios: [1, 1], product_formula: 'InP', product_name: '인화인듐(반도체)', reaction_type: 'combustion', animation: 'burn', color: '#808080' },
  { elements: ["Ba", "N", "O"], ratios: [1, 2, 6], product_formula: 'Ba(NO₃)₂', product_name: '질산바륨(녹색불꽃)', reaction_type: 'combustion', animation: 'burn', color: '#00FF00' },
  { elements: ["Al", "O", "H"], ratios: [1, 3, 3], product_formula: 'Al(OH)₃', product_name: '수산화알루미늄', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["In", "S"], ratios: [2, 3], product_formula: 'In₂S₃', product_name: '황화인듐', reaction_type: 'precipitation', animation: 'sink', color: '#FFD700' },
  { elements: ["C", "H"], ratios: [1, 4], product_formula: 'CH₄', product_name: '메테인(천연가스)', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["Ca", "S", "O"], ratios: [1, 1, 3], product_formula: 'CaSO₃', product_name: '아황산칼슘', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Mg", "S", "O"], ratios: [1, 1, 4], product_formula: 'MgSO₄', product_name: '황산마그네슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["H", "Br"], ratios: [1, 1], product_formula: 'HBr', product_name: '브롬화수소', reaction_type: 'gas', animation: 'bubble', color: '#E8E8E8' },
  { elements: ["Si", "O"], ratios: [1, 2], product_formula: 'SiO₂', product_name: '이산화규소', reaction_type: 'none', animation: 'none', color: '#E8E8E8' },
  { elements: ["Ga", "N"], ratios: [1, 1], product_formula: 'GaN', product_name: '질화갈륨(청색LED)', reaction_type: 'combustion', animation: 'burn', color: '#4169E1' },
  { elements: ["Ca", "S", "O"], ratios: [1, 1, 4], product_formula: 'CaSO₄·2H₂O', product_name: '석고(gypsum)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["C", "H", "O"], ratios: [5, 10, 4], product_formula: 'C₅H₁₀O₄', product_name: '데옥시리보스', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["Fe", "S"], ratios: [1, 1], product_formula: 'FeS', product_name: '황화철(II)', reaction_type: 'precipitation', animation: 'sink', color: '#2F2F2F' },
  { elements: ["S", "O"], ratios: [1, 3], product_formula: 'SO₃', product_name: '삼산화황', reaction_type: 'gas', animation: 'bubble', color: '#FFFFE0' },
  { elements: ["Ni", "Cl"], ratios: [1, 2], product_formula: 'NiCl₂', product_name: '염화니켈(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#3CB371' },
  { elements: ["Na", "P", "O"], ratios: [3, 1, 4], product_formula: 'Na₃PO₄', product_name: '인산나트륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Pb", "Te"], ratios: [1, 1], product_formula: 'PbTe', product_name: '텔루르화납(열전소자)', reaction_type: 'combustion', animation: 'burn', color: '#808080' },
  { elements: ["C", "H", "N", "O"], ratios: [6, 9, 3, 2], product_formula: 'C₆H₉N₃O₂', product_name: '히스티딘(일부)', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["Ag", "Cl"], ratios: [2, 2], product_formula: 'Ag₂Cl₂', product_name: '이염화은', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Ag", "O"], ratios: [2, 1], product_formula: 'Ag₂O', product_name: '산화은', reaction_type: 'precipitation', animation: 'sink', color: '#1A1A1A' },
  { elements: ["Hg", "S"], ratios: [1, 1], product_formula: 'HgS', product_name: '황화수은(주사)', reaction_type: 'precipitation', animation: 'sink', color: '#FF0000' },
  { elements: ["Bi", "S"], ratios: [2, 3], product_formula: 'Bi₂S₃', product_name: '황화비스무트', reaction_type: 'precipitation', animation: 'sink', color: '#2F2F2F' },
  { elements: ["Cu", "Sn"], ratios: [1, 1], product_formula: 'CuSn', product_name: '청동', reaction_type: 'combustion', animation: 'burn', color: '#CD7F32' },
  { elements: ["C", "O"], ratios: [1, 2], product_formula: 'CO₂', product_name: '이산화탄소', reaction_type: 'gas', animation: 'bubble', color: '#D0D0D0' },
  { elements: ["C", "H", "N"], ratios: [5, 5, 1], product_formula: 'C₅H₅N', product_name: '피리딘', reaction_type: 'dissolution', animation: 'dissolve', color: '#E0E0E0' },
  { elements: ["Ag", "C", "N"], ratios: [1, 1, 1], product_formula: 'AgCN', product_name: '사이안화은', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["C", "H", "N"], ratios: [6, 7, 1], product_formula: 'C₆H₇N', product_name: '아닐린', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5DEB3' },
  { elements: ["Pb", "F"], ratios: [1, 2], product_formula: 'PbF₂', product_name: '플루오린화납', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Hg", "S", "O"], ratios: [1, 1, 4], product_formula: 'HgSO₄', product_name: '황산수은(II)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5DC' },
  { elements: ["C", "H"], ratios: [4, 8], product_formula: 'C₄H₈', product_name: '뷰텐', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["Ba", "O", "H"], ratios: [1, 2, 2], product_formula: 'Ba(OH)₂', product_name: '수산화바륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["Cr", "O"], ratios: [2, 3], product_formula: 'Cr₂O₃', product_name: '산화크롬(III)', reaction_type: 'color_change', animation: 'colorchange', color: '#228B22' },
  { elements: ["Cu", "N", "O"], ratios: [1, 2, 6], product_formula: 'Cu(NO₃)₂', product_name: '질산구리(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#4169E1' },
  { elements: ["H", "I"], ratios: [1, 1], product_formula: 'HI', product_name: '아이오딘화수소', reaction_type: 'gas', animation: 'bubble', color: '#D4D4D4' },
  { elements: ["Li", "Co", "O"], ratios: [1, 1, 2], product_formula: 'LiCoO₂', product_name: '리튬코발트산화물(배터리양극)', reaction_type: 'dissolution', animation: 'colorchange', color: '#1A1A8B' },
  { elements: ["Sn", "O"], ratios: [1, 2], product_formula: 'SnO₂', product_name: '이산화주석', reaction_type: 'precipitation', animation: 'sink', color: '#F0F0F0' },
  { elements: ["H", "Cr", "O"], ratios: [2, 1, 4], product_formula: 'H₂CrO₄', product_name: '크롬산', reaction_type: 'color_change', animation: 'colorchange', color: '#FFD700' },
  { elements: ["N", "O"], ratios: [2, 1], product_formula: 'N₂O', product_name: '아산화질소', reaction_type: 'gas', animation: 'bubble', color: '#E0FFE0' },
  { elements: ["Na", "F"], ratios: [1, 1], product_formula: 'NaF', product_name: '플루오린화나트륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Fe", "F"], ratios: [1, 3], product_formula: 'FeF₃', product_name: '플루오린화철(III)', reaction_type: 'dissolution', animation: 'colorchange', color: '#F4C430' },
  { elements: ["Cs", "O"], ratios: [2, 1], product_formula: 'Cs₂O', product_name: '산화세슘', reaction_type: 'combustion', animation: 'burn', color: '#E8E8E8' },
  { elements: ["Ba", "Cr", "O"], ratios: [1, 1, 4], product_formula: 'BaCrO₄', product_name: '크롬산바륨', reaction_type: 'precipitation', animation: 'sink', color: '#FFD700' },
  { elements: ["Zn", "S", "O"], ratios: [1, 1, 4], product_formula: 'ZnSO₄', product_name: '황산아연', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["C", "H", "N", "O"], ratios: [9, 8, 4, 3], product_formula: 'C₉H₈N₄O₃', product_name: '테오필린', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["Fe", "Br"], ratios: [1, 2], product_formula: 'FeBr₂', product_name: '브롬화철(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#6B8E23' },
  { elements: ["Cd", "S", "O"], ratios: [1, 1, 4], product_formula: 'CdSO₄', product_name: '황산카드뮴', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Ba", "S"], ratios: [1, 1], product_formula: 'BaS', product_name: '황화바륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5DC' },
  { elements: ["N", "H", "O"], ratios: [1, 4, 3], product_formula: 'NH₄NO₃', product_name: '질산암모늄', reaction_type: 'explosion', animation: 'explode', color: '#FF6600' },
  { elements: ["C", "H", "O"], ratios: [5, 10, 2], product_formula: 'C₅H₁₀O₂', product_name: '발레르산', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["C", "H", "O"], ratios: [1, 4, 1], product_formula: 'CH₃OH', product_name: '메탄올', reaction_type: 'combustion', animation: 'burn', color: '#ADD8E6' },
  { elements: ["Na", "C"], ratios: [2, 2], product_formula: 'Na₂C₂', product_name: '탄화나트륨', reaction_type: 'explosion', animation: 'explode', color: '#F0F0F0' },
  { elements: ["Fe", "C"], ratios: [3, 1], product_formula: 'Fe₃C', product_name: '시멘타이트', reaction_type: 'combustion', animation: 'burn', color: '#808080' },
  { elements: ["C", "H", "O"], ratios: [5, 12, 5], product_formula: 'C₅H₁₂O₅', product_name: '자일리톨', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["C", "H", "N", "O"], ratios: [9, 13, 3, 3], product_formula: 'C₉H₁₃N₃O₃', product_name: '에피네프린', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["Mg", "O", "H"], ratios: [1, 2, 2], product_formula: 'Mg(OH)₂', product_name: '수산화마그네슘', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Ni", "O", "H"], ratios: [1, 2, 2], product_formula: 'Ni(OH)₂', product_name: '니켈수산화물(NiMH)', reaction_type: 'precipitation', animation: 'sink', color: '#90EE90' },
  { elements: ["Al", "P", "O"], ratios: [1, 1, 4], product_formula: 'AlPO₄', product_name: '인산알루미늄', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["H", "C", "O"], ratios: [2, 1, 3], product_formula: 'H₂CO₃', product_name: '탄산', reaction_type: 'gas', animation: 'bubble', color: '#D0E8FF' },
  { elements: ["Cd", "S"], ratios: [1, 1], product_formula: 'CdS', product_name: '황화카드뮴', reaction_type: 'precipitation', animation: 'sink', color: '#FFD700' },
  { elements: ["N", "H", "S", "O"], ratios: [2, 1, 1, 4], product_formula: '(NH₄)₂SO₄', product_name: '황산암모늄', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["C", "H", "O"], ratios: [18, 36, 2], product_formula: 'C₁₈H₃₆O₂', product_name: '스테아르산', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5DC' },
  { elements: ["Na", "Cl"], ratios: [1, 1], product_formula: 'NaCl', product_name: '암염(halite)', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["Mg", "Fe", "Si", "O"], ratios: [1, 1, 1, 3], product_formula: '(Mg,Fe)SiO₃', product_name: '사방휘석', reaction_type: 'precipitation', animation: 'sink', color: '#808080' },
  { elements: ["H", "S"], ratios: [2, 1], product_formula: 'H₂S', product_name: '황화수소', reaction_type: 'gas', animation: 'bubble', color: '#FFFFA0' },
  { elements: ["Al", "O"], ratios: [4, 3], product_formula: 'Al₂O₃', product_name: '산화알루미늄', reaction_type: 'combustion', animation: 'burn', color: '#E8E8E8' },
  { elements: ["Mg", "F"], ratios: [1, 2], product_formula: 'MgF₂', product_name: '플루오린화마그네슘', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Ni", "Al"], ratios: [3, 1], product_formula: 'Ni₃Al', product_name: '금속간화합물 Ni₃Al', reaction_type: 'combustion', animation: 'burn', color: '#C0C0C0' },
  { elements: ["Pb", "Cr", "O"], ratios: [1, 1, 4], product_formula: 'PbCrO₄', product_name: '크롬산납', reaction_type: 'precipitation', animation: 'sink', color: '#FFD700' },
  { elements: ["C", "H", "O"], ratios: [2, 6, 1], product_formula: 'C₂H₅OH', product_name: '에탄올(알코올)', reaction_type: 'combustion', animation: 'burn', color: '#ADD8E6' },
  { elements: ["Ca", "N", "O"], ratios: [1, 2, 6], product_formula: 'Ca(NO₃)₂', product_name: '질산칼슘(비료)', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["Cu", "Zn"], ratios: [1, 1], product_formula: 'CuZn', product_name: '황동(브라스)', reaction_type: 'combustion', animation: 'burn', color: '#DAA520' },
  { elements: ["Fe", "Cl"], ratios: [1, 2], product_formula: 'FeCl₂', product_name: '염화철(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#6B8E6B' },
  { elements: ["K", "Cr", "O"], ratios: [2, 2, 7], product_formula: 'K₂Cr₂O₇', product_name: '중크롬산칼륨', reaction_type: 'color_change', animation: 'colorchange', color: '#FF4500' },
  { elements: ["Fe", "C"], ratios: [3, 1], product_formula: 'Fe₃C', product_name: '시멘타이트', reaction_type: 'combustion', animation: 'burn', color: '#808080' },
  { elements: ["Fe", "S", "O"], ratios: [2, 3, 12], product_formula: 'Fe₂(SO₄)₃', product_name: '황산철(III)', reaction_type: 'dissolution', animation: 'colorchange', color: '#FFD700' },
  { elements: ["Ti", "O", "H"], ratios: [1, 4, 4], product_formula: 'Ti(OH)₄', product_name: '수산화타이타늄', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["C", "H", "O"], ratios: [1, 2, 2], product_formula: 'HCOOH', product_name: '폼산(개미산)', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["Hg", "N", "O"], ratios: [1, 2, 6], product_formula: 'Hg(NO₃)₂', product_name: '질산수은(II)', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Mn", "Cl"], ratios: [1, 2], product_formula: 'MnCl₂', product_name: '염화망간(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#FFB6C1' },
  { elements: ["Ag", "C", "O"], ratios: [2, 1, 3], product_formula: 'Ag₂CO₃', product_name: '탄산은', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5DC' },
  { elements: ["Fe", "I"], ratios: [1, 2], product_formula: 'FeI₂', product_name: '아이오딘화철(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#808000' },
  { elements: ["C", "H"], ratios: [14, 10], product_formula: 'C₁₄H₁₀', product_name: '안트라센', reaction_type: 'combustion', animation: 'burn', color: '#F5F5DC' },
  { elements: ["Au", "O"], ratios: [2, 3], product_formula: 'Au₂O₃', product_name: '산화금(III)', reaction_type: 'precipitation', animation: 'sink', color: '#808000' },
  { elements: ["Ca", "F"], ratios: [1, 2], product_formula: 'CaF₂', product_name: '플루오린화칼슘(형석)', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["Al", "S"], ratios: [2, 3], product_formula: 'Al₂S₃', product_name: '황화알루미늄', reaction_type: 'precipitation', animation: 'sink', color: '#FFD700' },
  { elements: ["Cr", "C"], ratios: [7, 3], product_formula: 'Cr₇C₃', product_name: '탄화크롬', reaction_type: 'combustion', animation: 'burn', color: '#808080' },
  { elements: ["H", "O"], ratios: [2, 1], product_formula: 'H₂O', product_name: '물', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["Sn", "S"], ratios: [1, 1], product_formula: 'SnS', product_name: '황화주석(II)', reaction_type: 'precipitation', animation: 'sink', color: '#2F2F2F' },
  { elements: ["Sr", "O", "H"], ratios: [1, 2, 2], product_formula: 'Sr(OH)₂', product_name: '수산화스트론튬', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["B", "C"], ratios: [4, 1], product_formula: 'B₄C', product_name: '탄화붕소', reaction_type: 'combustion', animation: 'burn', color: '#1A1A1A' },
  { elements: ["Ca", "S"], ratios: [1, 1], product_formula: 'CaS', product_name: '황화칼슘', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5DC' },
  { elements: ["Si", "C"], ratios: [1, 1], product_formula: 'SiC', product_name: '탄화규소(카보런덤)', reaction_type: 'combustion', animation: 'burn', color: '#1A1A1A' },
  { elements: ["H", "Cl", "O"], ratios: [1, 1, 1], product_formula: 'HClO', product_name: '하이포염소산', reaction_type: 'dissolution', animation: 'dissolve', color: '#E8FFE8' },
  { elements: ["Fe", "Cl"], ratios: [1, 3], product_formula: 'FeCl₃', product_name: '염화철(III)', reaction_type: 'dissolution', animation: 'colorchange', color: '#8B4513' },
  { elements: ["C", "H", "O"], ratios: [6, 12, 6], product_formula: 'C₆H₁₂O₆', product_name: '과당(프럭토스)', reaction_type: 'dissolution', animation: 'dissolve', color: '#ADD8E6' },
  { elements: ["C", "H", "O"], ratios: [2, 4, 1], product_formula: 'CH₃CHO', product_name: '아세트알데히드', reaction_type: 'gas', animation: 'bubble', color: '#E0E0E0' },
  { elements: ["Cu", "S", "O"], ratios: [1, 1, 4], product_formula: 'CuSO₄', product_name: '황산구리(II)', reaction_type: 'dissolution', animation: 'colorchange', color: '#1E90FF' },
  { elements: ["C", "H", "N", "O"], ratios: [3, 7, 1, 2], product_formula: 'C₃H₇NO₂', product_name: '알라닌', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["Pb", "Cl"], ratios: [1, 4], product_formula: 'PbCl₄', product_name: '염화납(IV)', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5E050' },
  { elements: ["C", "Cl"], ratios: [1, 4], product_formula: 'CCl₄', product_name: '사염화탄소', reaction_type: 'dissolution', animation: 'dissolve', color: '#E0E0E0' },
  { elements: ["Bi", "Te"], ratios: [2, 3], product_formula: 'Bi₂Te₃', product_name: '텔루르화비스무트(열전)', reaction_type: 'combustion', animation: 'burn', color: '#808080' },
  { elements: ["Na", "S", "O"], ratios: [2, 1, 3], product_formula: 'Na₂SO₃', product_name: '아황산나트륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["H", "I", "O"], ratios: [1, 1, 3], product_formula: 'HIO₃', product_name: '아이오딘산', reaction_type: 'dissolution', animation: 'dissolve', color: '#E0E0FF' },
  { elements: ["Mn", "O"], ratios: [1, 1], product_formula: 'MnO', product_name: '산화망간(II)', reaction_type: 'precipitation', animation: 'sink', color: '#3E3535' },
  { elements: ["K", "Br"], ratios: [1, 1], product_formula: 'KBr', product_name: '브롬화칼륨', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Ca", "P", "O"], ratios: [3, 2, 8], product_formula: 'Ca₃(PO₄)₂', product_name: '인산칼슘', reaction_type: 'precipitation', animation: 'sink', color: '#F5F5F5' },
  { elements: ["C", "H"], ratios: [6, 14], product_formula: 'C₆H₁₄', product_name: '헥세인', reaction_type: 'combustion', animation: 'burn', color: '#E0E0E0' },
  { elements: ["N", "H", "I"], ratios: [1, 4, 1], product_formula: 'NH₄I', product_name: '아이오딘화암모늄', reaction_type: 'dissolution', animation: 'dissolve', color: '#D0E8FF' },
  { elements: ["Zn", "S"], ratios: [1, 1], product_formula: 'ZnS', product_name: '섬아연석(sphalerite)', reaction_type: 'precipitation', animation: 'sink', color: '#F5DEB3' },
  { elements: ["Ti", "Cl"], ratios: [1, 4], product_formula: 'TiCl₄', product_name: '염화타이타늄', reaction_type: 'dissolution', animation: 'dissolve', color: '#F5F5F5' },
  { elements: ["K", "Mn", "O"], ratios: [2, 1, 4], product_formula: 'KMnO₄', product_name: '과망간산칼륨', reaction_type: 'color_change', animation: 'colorchange', color: '#8B008B' },
]
